[build]
  command = "next build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[build.environment]
  NEXT_USE_NETLIFY_CACHE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[secrets]
  omit_keys = [
    "NEXT_PUBLIC_EMAIL_JS_PUBLIC_KEY",
    "NEXT_PUBLIC_EMAIL_JS_SERVICE_ID_CONTACT_US",
    "NEXT_PUBLIC_EMAIL_JS_SERVICE_ID_GET_IN_TOUCH",
    "NEXT_PUBLIC_EMAIL_JS_TEMPLATE_ID"
  ]
