import {
  faArrowDownWideShort,
  faArrowUpShortWide,
  faIndianRupeeSign,
  faStar,
} from "@fortawesome/free-solid-svg-icons";

export interface ChildMenu {
  id: number;
  title: string;
  navigation: string;
  description: string;
}

export interface Menus {
  id: number;
  title: string;
  navigation: string;
  description?: string;
  childMenus?: ChildMenu[];
}

export const menuForDesktopItems: Menus[] = [
  {
    id: 1,
    title: "Festive Edition - SALE!",
    navigation: "/category/festive-edition",
    description:
      "Celebrate the season of joy with our Festive Edition – a vibrant mix of art, drawings, resin pieces, home décor, and crafts to brighten your celebrations",
  },
  {
    id: 2,
    title: "Limited Edition - SALE!",
    navigation: "/category/limited-edition",
    description:
      "Discover our Limited Edition – a rare collection of art, unique drawings, resin creations, and handcrafted décor pieces, designed to bring exclusivity and elegance to your space.",
  },
  {
    id: 3,
    title: "Latest Drops",
    navigation: "/category/newly-launched",
    description:
      "Explore our Latest Drops – a fresh curation of art, contemporary drawings, resin accents, and handcrafted décor. Each piece is newly introduced to bring modern charm and creative flair into your collection.",
  },
  {
    id: 4,
    title: "Painting",
    navigation: "/painting",
    childMenus: [
      {
        id: 1,
        title: "Oil Painting",
        navigation: "/painting/oil-painting",
        description:
          "Classic oil paintings with rich textures and timeless beauty for art enthusiasts.",
      },
      {
        id: 2,
        title: "Watercolor Painting",
        navigation: "/painting/watercolor-painting",
        description:
          "Delicate watercolor art with soft tones and expressive brushwork.",
      },
      {
        id: 3,
        title: "Acrylic Painting",
        navigation: "/painting/acrylic-painting",
        description:
          "Bold and vibrant acrylic paintings that bring contemporary energy to your walls.",
      },
      {
        id: 4,
        title: "Portrait Painting",
        navigation: "/painting/portrait-painting",
        description:
          "Personalized and artistic portraits capturing unique emotions and expressions.",
      },
      {
        id: 5,
        title: "Landscape Painting",
        navigation: "/painting/landscape-painting",
        description:
          "Scenic landscape art that transports you to serene and picturesque views.",
      },
      {
        id: 6,
        title: "Abstract Painting",
        navigation: "/painting/abstract-painting",
        description:
          "Modern abstract art with imaginative forms and vibrant compositions.",
      },
    ],
  },
  {
    id: 5,
    title: "Resin Art",
    navigation: "/resin-art",
    childMenus: [
      {
        id: 1,
        title: "Keychains",
        navigation: "/resin-art/resin-keychain",
        description:
          "Stylish resin keychains crafted with unique patterns and colors.",
      },
      {
        id: 2,
        title: "Flower Preservation",
        navigation: "/resin-art/resin-flowers",
        description:
          "Beautifully preserved flowers in resin, keeping memories timeless.",
      },
      {
        id: 3,
        title: "Resin Tables",
        navigation: "/resin-art/resin-tables",
        description:
          "Elegant resin tables blending function with artistic design.",
      },
      {
        id: 4,
        title: "Wall Clocks",
        navigation: "/resin-art/resin-clocks",
        description:
          "Artistic resin wall clocks that add a modern touch to your home.",
      },
      {
        id: 5,
        title: "Jewelry & Accessories",
        navigation: "/resin-art/resin-jewelry",
        description:
          "Handcrafted resin jewelry and accessories for a bold fashion statement.",
      },
      {
        id: 6,
        title: "Coasters",
        navigation: "/resin-art/resin-coasters",
        description:
          "Durable and artistic resin coasters for your stylish tabletops.",
      },
    ],
  },
  {
    id: 6,
    title: "Home Decor",
    navigation: "/home-decor",
    childMenus: [
      {
        id: 1,
        title: "Personal Quote Frames",
        navigation: "/home-decor/frames",
        description:
          "Customized frames with your favorite quotes to inspire and decorate.",
      },
      {
        id: 2,
        title: "Bedroom Wall Hangings",
        navigation: "/home-decor/wall-hangings",
        description:
          "Decorative wall hangings that bring warmth and style to your bedroom.",
      },
      {
        id: 3,
        title: "Living Room Decor",
        navigation: "/home-decor/living-room",
        description:
          "Chic and creative décor to elevate the ambiance of your living room.",
      },
      {
        id: 4,
        title: "Macrame Hangings",
        navigation: "/home-decor/macrame",
        description:
          "Handwoven macrame art for a cozy and bohemian touch to any space.",
      },
      {
        id: 5,
        title: "Tapestry Wall Art",
        navigation: "/home-decor/tapestry-wall-art",
        description:
          "Intricate tapestry designs to bring color and culture to your walls.",
      },
      {
        id: 6,
        title: "Festive Wall Hangings",
        navigation: "/home-decor/festive-hangings",
        description:
          "Joyful and decorative wall hangings perfect for seasonal celebrations.",
      },
    ],
  },
  {
    id: 7,
    title: "Crafts",
    navigation: "/craft",
    childMenus: [
      {
        id: 1,
        title: "Paper Craft",
        navigation: "/craft/paper-craft",
        description:
          "Creative paper crafts with intricate designs and handmade charm.",
      },
      {
        id: 2,
        title: "Clay Modeling",
        navigation: "/craft/clay-craft",
        description:
          "Expressive clay models shaped with artistic detail and care.",
      },
      {
        id: 3,
        title: "Handmade Jewelry",
        navigation: "/craft/jewelry-craft",
        description:
          "Unique handmade jewelry crafted from creative materials and designs.",
      },
      {
        id: 4,
        title: "Wood Art",
        navigation: "/craft/wood-craft",
        description:
          "Elegant wooden art pieces showcasing natural beauty and craftsmanship.",
      },
      {
        id: 5,
        title: "Fabric Art",
        navigation: "/craft/fabric-craft",
        description:
          "Colorful and textured fabric art adding creativity to your décor.",
      },
    ],
  },
  { id: 8, title: "Contact Us", navigation: "/contact-us" },
];

export const DummySearchValues = [
  { id: 1, label: "Apple", value: "apple" },
  { id: 2, label: "Banana", value: "banana" },
  { id: 3, label: "Cherry", value: "cherry" },
  { id: 4, label: "Dragonfruit", value: "dragonfruit" },
  { id: 5, label: "Elderberry", value: "elderberry" },
  { id: 6, label: "Fig", value: "fig" },
  { id: 7, label: "Grapes", value: "grapes" },
  { id: 8, label: "Honeydew", value: "honeydew" },
  { id: 9, label: "Mango", value: "mango" },
  { id: 10, label: "Pineapple", value: "pineapple" },
];

export const LandingPageContent = [
  {
    id: 1,
    imageLink: "/unsplashImage1.jpg",
    imageDescription:
      "Step into a Dreamy Garden of Floral Tea cups, each skillfully handpainted.",
    imageTitle: "Crafts",
    imageButton: "Explore",
    imageNavigation: "/craft/paper-craft",
  },
  {
    id: 2,
    imageLink: "/unsplashImage2.jpg",
    imageDescription:
      "Discover stunning portraits and modern artwork that bring stories to life.",
    imageTitle: "Paintings",
    imageButton: "Shop Now",
    imageNavigation: "/painting/oil-painting",
  },
  {
    id: 3,
    imageLink: "/unsplashImage3.jpg",
    imageDescription:
      "Dive into the world of resin art, where creativity meets glossy perfection.",
    imageTitle: "Resin Art",
    imageButton: "Browse",
    imageNavigation: "/resin-art/resin-jewelry",
  },
  {
    id: 4,
    imageLink: "/unsplashImage4.jpg",
    imageDescription:
      "Enhance your living space with unique and artistic home décor pieces.",
    imageTitle: "Home Décor",
    imageButton: "Discover",
    imageNavigation: "/home-decor/frames",
  },
];

export const categories =
  menuForDesktopItems
    ?.filter((item) => item?.childMenus?.length)
    ?.map((item) => item.title) ?? [];

export const sortOptions = [
  { label: "Best Selling", icon: faStar },
  { label: "Below 1000", icon: faIndianRupeeSign },
  { label: "Low to High", icon: faArrowUpShortWide },
  { label: "High to Low", icon: faArrowDownWideShort },
];

export const products = [
  {
    id: 1,
    title: "Classic Oil Landscape",
    price: "5199",
    image: "/unsplashImage1.jpg",
    type: "Oil Painting",
    description: "Handmade oil painting with deep textures and natural tones.",
    isAvailable: true,
    details: [
      "Painted on stretched canvas",
      "Durable oil pigments",
      "Rich brush textures",
    ],
    customizationAllowed: true,
    customized_details: "Custom scenery or colors can be requested.",
    isSale: true,
    saleDiscount: 15,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 2,
    title: "Abstract Oil Masterpiece",
    price: "7299",
    image: "/unsplashImage2.jpg",
    type: "Oil Painting",
    description: "Bold abstract oil painting full of expressive strokes.",
    isAvailable: false,
    details: ["Large wall art", "Palette knife strokes", "Premium finish"],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 3,
    title: "Watercolor Floral Bloom",
    price: "2399",
    image: "/unsplashImage3.jpg",
    type: "Watercolor Painting",
    description: "Gentle floral watercolor on textured paper.",
    isAvailable: true,
    details: [
      "Mounted on ivory frame",
      "Soft pastel tones",
      "Lightweight décor piece",
    ],
    customizationAllowed: true,
    customized_details: "Choose preferred flowers and shades.",
    isSale: true,
    saleDiscount: 10,
    isLatest: true,
    mostSeller: true,
  },
  {
    id: 4,
    title: "Watercolor Seascape",
    price: "3599",
    image: "/unsplashImage4.jpg",
    type: "Watercolor Painting",
    description: "Serene seaside painting with calm hues.",
    isAvailable: false,
    details: ["Premium watercolor pigments", "Matte finish", "Framed artwork"],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: false,
  },
  {
    id: 5,
    title: "Vibrant Acrylic Burst",
    price: "4199",
    image: "/unsplashImage1.jpg",
    type: "Acrylic Painting",
    description: "Colorful acrylic artwork full of energy.",
    isAvailable: true,
    details: ["Bright hues", "Thick acrylic strokes", "Contemporary style"],
    customizationAllowed: true,
    customized_details: "Pick your color palette.",
    isSale: true,
    saleDiscount: 20,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 6,
    title: "Abstract Acrylic Flow",
    price: "4799",
    image: "/unsplashImage2.jpg",
    type: "Acrylic Painting",
    description: "Free-flow acrylic design with bold tones.",
    isAvailable: true,
    details: [
      "Dynamic flow patterns",
      "Premium stretched canvas",
      "Unique handmade work",
    ],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 7,
    title: "Portrait Commission (Single)",
    price: "8499",
    image: "/unsplashImage3.jpg",
    type: "Portrait Painting",
    description: "Personalized portrait with lifelike details.",
    isAvailable: true,
    details: ["Painted on demand", "Captures likeness", "Durable pigments"],
    customizationAllowed: true,
    customized_details: "Send your photo for personalization.",
    isSale: true,
    saleDiscount: 5,
    isLatest: true,
    mostSeller: true,
  },
  {
    id: 8,
    title: "Couple Portrait",
    price: "11999",
    image: "/unsplashImage4.jpg",
    type: "Portrait Painting",
    description: "Beautifully detailed couple portrait painting.",
    isAvailable: false,
    details: ["Romantic gift", "Oil on canvas", "Hand-detailed"],
    customizationAllowed: true,
    customized_details: "Include special backgrounds.",
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: false,
  },
  {
    id: 9,
    title: "Mountain Landscape",
    price: "5599",
    image: "/unsplashImage1.jpg",
    type: "Landscape Painting",
    description: "Scenic mountain and lake view painting.",
    isAvailable: true,
    details: ["Natural scenery", "Earthy tones", "Large format"],
    customizationAllowed: false,
    isSale: true,
    saleDiscount: 25,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 10,
    title: "Sunset Horizon",
    price: "4899",
    image: "/unsplashImage2.jpg",
    type: "Landscape Painting",
    description: "Dramatic sunset landscape with warm colors.",
    isAvailable: true,
    details: ["Gradient blending", "Vibrant skies", "Wall-mount ready"],
    customizationAllowed: true,
    customized_details: "Customize sky tones and size.",
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 11,
    title: "Geometric Abstract",
    price: "3799",
    image: "/unsplashImage3.jpg",
    type: "Abstract Painting",
    description: "Sharp geometric abstract painting.",
    isAvailable: true,
    details: ["Bold shapes", "Bright contrast colors", "Acrylic on canvas"],
    customizationAllowed: false,
    isSale: true,
    saleDiscount: 12,
    isLatest: true,
    mostSeller: true,
  },
  {
    id: 12,
    title: "Color Splash Abstract",
    price: "4599",
    image: "/unsplashImage4.jpg",
    type: "Abstract Painting",
    description: "Random splash-style abstract for modern spaces.",
    isAvailable: false,
    details: ["Unique splatter technique", "UV-protected coating"],
    customizationAllowed: true,
    customized_details: "Choose your preferred dominant colors.",
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: false,
  },
  {
    id: 13,
    title: "Glitter Resin Keychain",
    price: "899",
    image: "/unsplashImage1.jpg",
    type: "Keychains",
    description: "Stylish glitter-filled resin keychain.",
    isAvailable: true,
    details: ["Durable epoxy resin", "Custom initials option"],
    customizationAllowed: true,
    customized_details: "Add name letters or charms.",
    isSale: true,
    saleDiscount: 18,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 14,
    title: "Heart Resin Keychain",
    price: "999",
    image: "/unsplashImage2.jpg",
    type: "Keychains",
    description: "Heart-shaped resin keychain with dried flowers.",
    isAvailable: false,
    details: ["Real flowers", "Portable size", "Perfect gift"],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 15,
    title: "Rose Preservation Block",
    price: "1699",
    image: "/unsplashImage3.jpg",
    type: "Flower Preservation",
    description: "Preserved rose in crystal-clear resin.",
    isAvailable: true,
    details: ["Long-lasting preservation", "Gift-ready box"],
    customizationAllowed: true,
    customized_details: "Bring your own flower for preservation.",
    isSale: true,
    saleDiscount: 8,
    isLatest: true,
    mostSeller: true,
  },
  {
    id: 16,
    title: "Bouquet in Resin Frame",
    price: "2499",
    image: "/unsplashImage4.jpg",
    type: "Flower Preservation",
    description: "Mini bouquet preserved in resin wall frame.",
    isAvailable: true,
    details: ["Wall hanging design", "Protective resin coating"],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: false,
  },
  {
    id: 17,
    title: "Mini Resin Table",
    price: "7799",
    image: "/unsplashImage1.jpg",
    type: "Resin Tables",
    description: "Handmade resin side table with ocean design.",
    isAvailable: false,
    details: ["Wood + resin mix", "Durable epoxy finish"],
    customizationAllowed: true,
    customized_details: "Select colors for resin pour.",
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 18,
    title: "Resin Coffee Table",
    price: "13299",
    image: "/unsplashImage2.jpg",
    type: "Resin Tables",
    description: "Unique resin coffee table with wave art.",
    isAvailable: true,
    details: ["Premium wood base", "Ocean art resin top"],
    customizationAllowed: false,
    isSale: true,
    saleDiscount: 30,
    isLatest: true,
    mostSeller: true,
  },
  {
    id: 19,
    title: "Resin Wall Clock",
    price: "3299",
    image: "/unsplashImage3.jpg",
    type: "Wall Clocks",
    description: "Resin wall clock with modern swirl design.",
    isAvailable: true,
    details: ["Quartz movement", "12-inch diameter"],
    customizationAllowed: true,
    customized_details: "Pick your color swirl.",
    isSale: true,
    saleDiscount: 5,
    isLatest: false,
    mostSeller: false,
  },
  {
    id: 20,
    title: "Galaxy Resin Clock",
    price: "3699",
    image: "/unsplashImage4.jpg",
    type: "Wall Clocks",
    description: "Cosmic galaxy resin effect wall clock.",
    isAvailable: false,
    details: ["Glow effect in dark", "Silent sweep mechanism"],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: true,
    mostSeller: true,
  },
  {
    id: 21,
    title: "Resin Pendant Necklace",
    price: "1499",
    image: "/unsplashImage1.jpg",
    type: "Jewelry & Accessories",
    description: "Handcrafted resin pendant with gold flakes.",
    isAvailable: true,
    details: ["Includes metal chain", "Lightweight resin body"],
    customizationAllowed: true,
    customized_details: "Choose pendant shape and flakes.",
    isSale: false,
    saleDiscount: 0,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 22,
    title: "Resin Earrings",
    price: "999",
    image: "/unsplashImage2.jpg",
    type: "Jewelry & Accessories",
    description: "Trendy resin earrings with embedded flowers.",
    isAvailable: true,
    details: ["Nickel-free hooks", "Handmade unique designs"],
    customizationAllowed: false,
    isSale: true,
    saleDiscount: 25,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 23,
    title: "Resin Coaster Set",
    price: "1699",
    image: "/unsplashImage3.jpg",
    type: "Coasters",
    description: "Ocean wave resin coasters (set of 4).",
    isAvailable: false,
    details: ["Heat resistant", "Glossy finish", "Durable"],
    customizationAllowed: true,
    customized_details: "Pick colors and set size.",
    isSale: false,
    saleDiscount: 0,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 24,
    title: "Gold Flake Resin Coasters",
    price: "1899",
    image: "/unsplashImage4.jpg",
    type: "Coasters",
    description: "Elegant resin coasters with golden flakes.",
    isAvailable: true,
    details: ["High-gloss coating", "Perfect for gifts"],
    customizationAllowed: false,
    isSale: true,
    saleDiscount: 12,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 25,
    title: "Custom Quote Frame",
    price: "1099",
    image: "/unsplashImage1.jpg",
    type: "Personal Quote Frames",
    description: "Inspirational quote printed in a sleek frame.",
    isAvailable: true,
    details: ["Premium matte print", "Wooden border frame"],
    customizationAllowed: true,
    customized_details: "Submit your own text/quote.",
    isSale: true,
    saleDiscount: 10,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 26,
    title: "Motivational Quote Frame",
    price: "1399",
    image: "/unsplashImage2.jpg",
    type: "Personal Quote Frames",
    description: "Bold typography wall quote.",
    isAvailable: false,
    details: ["Gloss finish", "Wall mount ready"],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 27,
    title: "Macrame Wall Hanging",
    price: "1699",
    image: "/unsplashImage3.jpg",
    type: "Macrame Hangings",
    description: "Handwoven macrame art piece for cozy vibes.",
    isAvailable: true,
    details: ["Made with cotton rope", "Eco-friendly"],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 28,
    title: "Large Boho Macrame",
    price: "2799",
    image: "/unsplashImage4.jpg",
    type: "Macrame Hangings",
    description: "Oversized macrame piece for big walls.",
    isAvailable: true,
    details: ["Bohemian style", "Light beige cotton"],
    customizationAllowed: true,
    customized_details: "Choose rope colors and size.",
    isSale: true,
    saleDiscount: 15,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 29,
    title: "Festive Hanging Lantern",
    price: "909",
    image: "/unsplashImage1.jpg",
    type: "Festive Wall Hangings",
    description: "Colorful wall lantern décor for festivals.",
    isAvailable: false,
    details: ["Bright LED included", "Reusable festive décor"],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 30,
    title: "Handmade Festive Toran",
    price: "1399",
    image: "/unsplashImage2.jpg",
    type: "Festive Wall Hangings",
    description: "Traditional toran wall hanging for celebrations.",
    isAvailable: true,
    details: ["Made with beads & cloth", "Lightweight & reusable"],
    customizationAllowed: true,
    customized_details: "Pick colors and text banner.",
    isSale: true,
    saleDiscount: 20,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 31,
    title: "Origami Birds Pack",
    price: "599",
    image: "/unsplashImage3.jpg",
    type: "Paper Craft",
    description: "Set of 12 colorful origami birds.",
    isAvailable: true,
    details: ["Eco-friendly paper", "Handmade pieces"],
    customizationAllowed: false,
    isSale: true,
    saleDiscount: 15,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 32,
    title: "Paper Flower Decor",
    price: "799",
    image: "/unsplashImage4.jpg",
    type: "Paper Craft",
    description: "Handcrafted paper flower décor set.",
    isAvailable: false,
    details: ["Bright colors", "Reusable design"],
    customizationAllowed: true,
    customized_details: "Choose colors and bouquet size.",
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 33,
    title: "Clay Figurine Set",
    price: "1099",
    image: "/unsplashImage1.jpg",
    type: "Clay Modeling",
    description: "Miniature clay figurine collection.",
    isAvailable: true,
    details: ["Air-dry clay", "Hand painted"],
    customizationAllowed: true,
    isSale: false,
    saleDiscount: 0,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 34,
    title: "Clay Mini Pottery",
    price: "699",
    image: "/unsplashImage2.jpg",
    type: "Clay Modeling",
    description: "Handmade mini clay pots with artistic finish.",
    isAvailable: true,
    details: ["Eco-friendly terracotta", "Artisanal work"],
    customizationAllowed: false,
    isSale: true,
    saleDiscount: 25,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 35,
    title: "Handmade Beaded Necklace",
    price: "1499",
    image: "/unsplashImage3.jpg",
    type: "Handmade Jewelry",
    description: "Beautiful handmade jewelry from beads & fabric.",
    isAvailable: true,
    details: ["Lightweight & trendy", "Eco-friendly"],
    customizationAllowed: true,
    customized_details: "Choose bead color & length.",
    isSale: false,
    saleDiscount: 0,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 36,
    title: "Fabric Wrapped Bracelet",
    price: "899",
    image: "/unsplashImage4.jpg",
    type: "Handmade Jewelry",
    description: "Unique fabric-based bracelet design.",
    isAvailable: false,
    details: ["Adjustable size", "Multiple fabrics available"],
    customizationAllowed: false,
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 37,
    title: "Wooden Wall Art",
    price: "2199",
    image: "/unsplashImage1.jpg",
    type: "Wood Art",
    description: "Polished wooden carving for home décor.",
    isAvailable: true,
    details: ["Hand-carved", "Natural finish"],
    customizationAllowed: false,
    isSale: true,
    saleDiscount: 5,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 38,
    title: "Rustic Wood Sculpture",
    price: "2799",
    image: "/unsplashImage2.jpg",
    type: "Wood Art",
    description: "Rustic handcrafted wooden sculpture.",
    isAvailable: false,
    details: ["Made from reclaimed wood", "Durable finish"],
    customizationAllowed: true,
    customized_details: "Choose design patterns.",
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
  {
    id: 39,
    title: "Fabric Wall Hanging",
    price: "1499",
    image: "/unsplashImage3.jpg",
    type: "Fabric Art",
    description: "Colorful wall hanging made with fabric patches.",
    isAvailable: true,
    details: ["Hand-stitched", "Vibrant colors"],
    customizationAllowed: false,
    isSale: true,
    saleDiscount: 18,
    isLatest: true,
    mostSeller: false,
  },
  {
    id: 40,
    title: "Fabric Collage Art",
    price: "1799",
    image: "/unsplashImage4.jpg",
    type: "Fabric Art",
    description: "Collage made from layered fabrics.",
    isAvailable: false,
    details: ["Mixed texture fabrics", "Unique handmade work"],
    customizationAllowed: true,
    customized_details: "Provide your color scheme.",
    isSale: false,
    saleDiscount: 0,
    isLatest: false,
    mostSeller: true,
  },
];
